# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# SEO settings
title: Core Dumped
tagline: Notes on Computer Science and Electronics
description: >-
  A collection of my personal notes on computer science, electronic engineering, 
  and everything in-between. Psuedointellect, regrettable puns, head-scratching,
  and poorly-written code abound. Enjoy!
url: "https://www.brighamcampbell.com"
lang: en_US

baseurl: "" # the subpath of your site, e.g. /blog
google_analytics: UA-155275688-1
email: me@brighamcampbell.com

# Build settings
markdown: kramdown
theme: konkai
plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
